### ISSUE TITLE
Building the CLI takes a long time

### ISSUE THREAD

**Issue by aloverso** [ambientlight/amplify-cli-action#20]
I'm using this package and really appreciate it, but I noticed that the first step of my Github Actions pipeline is now to build this action from Dockerfile, which is regularly taking 2-3 minutes for every deploy.

![image](https://user-images.githubusercontent.com/6563663/114758647-34356080-9d2b-11eb-8720-e6c6a02790be.png)

Is there any way for this to be cached, especially between different jobs in the same pipeline? Or for it to be changed so that it doesn't need to build every time?

**Comment by ambientlight** [comment]
@aloverso: It feels like it should exists by this point, is there any way how https://github.com/whoan/docker-build-with-cache-action#example-with-more-options can be used before this action in the workflow?

**Comment by johnf** [comment]
I have a good solution for this in #24 Rather than point at the Dockerfile. Build the container and push it to the publick github docker registry. This drops build time down to sub 5 seconds as it only needs to pull the registry image

@ambientlight I added instruction in the README on how you would push to the registry. You would also need to follow instructions at https://docs.github.com/en/packages/working-with-a-github-packages-registry/enabling-improved-container-support-with-the-container-registry to set things up if you haven't before.

MIght be worth even adding github action to this repo to auto build and push on creating of a tag

**Comment by ambientlight** [comment]
Fixed by #24 in [0.3.0](https://github.com/ambientlight/amplify-cli-action/releases/tag/0.3.0)
